  displayName: Comments
  description: |
    Handle the COMMENT objects.

    {cid} refers to the comments's unique identifier.
  get:
    queryParameters:
      q:
        description: Search phrase to look for products
        type: string
        required: false
    description: |
      Retrieve Comments based on Query paramters.
    responses:
      200:
        body:
          application/vnd.mogger.post:
            example: !include json/posts.comments.query.json
  /{cid}:
    uriParameters:
      cid:
        type: string
        description: comment identifier

    get:
      description: |
        Find a comment by it's comment id (cid).
      body:
        application/vnd.mogger.comment:
          example: |
            {
              "_links": {
                "self":{"href":"/api/comments/{cid}"},
              },
              "_status":{
                "http_code": 200,
                "content":"success",
                "error_code": null
              },
              "author":"comment author's username",
              "content":"comment content markdown",
              "createdAt":"created timestamp"
            }
    put:
      description: |
        Update a comment by it's comment id (cid).
      body:
        application/vnd.mogger.comment:
          example: |
            {
              "content":"new markdown content"
            }
      responses:
        200:
          body:
            application/vnd.mogger.comment:
              example: |
                {
                  "_links": {
                  "self":{"href":"/api/comments/{cid}"},
                  }
                  "_status":{
                    "http_code": 200,
                    "content":"success",
                    "error_code": null
                  },
                  "author":"comment author's username",
                  "content":"comment content markdown",
                  "createdAt":"created timestamp"
                }
        401:
          body:
            application/vnd.mogger.comment:
              example: !include json/401.json
        403:
          body:
            application/vnd.mogger.comment:
              example: !include json/403.json
        404:
          body:
            application/vnd.mogger.comment:
              example: !include json/404.json
    delete:
      description: Delete a post by it's post id (pid).
      responses:
        200:
          body:
            application/vnd.mogger.comment:
              example: |
                {
                  "_status": {
                    "http_code": 200,
                    "content": "success"
                  }
                }
        401:
          body:
            application/vnd.mogger.comment:
              example: !include json/401.json
        403:
          body:
            application/vnd.mogger.comment:
              example: !include json/403.json
        404:
          body:
            application/vnd.mogger.comment:
              example: !include json/404.json
  /{cid}/reply:
    uriParameters:
      cid:
        type: string
        description: comment identifier
    post:
      body:
        application/vnd.mogger.comment:
          example: |
            {
              "content":"reply markdown content"
            }
      responses:
        200:
          body:
            application/vnd.mogger.comment:
              example: |
                {
                  "_status":{
                    "http_code":200,
                    "content":"success",
                    "error_code":null
                  },
                  "_links":{
                    "_self":{"href":"/api/comments/{cid}"}
                  }
                  "author":"reply author",
                  "content":"content of reply",
                  "createdAt":"time reply was created"
                }
        401:
          body:
            application/vnd.mogger.comment:
              example: !include json/401.json
